development:
  adapter: postgresql
  encoding: unicode
  database: practice_app_development
  pool: 5
  username: postgres
  password: admin
  host: localhost
 
test:
  adapter: postgresql
  encoding: unicode
  database: practice_app_test
  pool: 5
  username: postgres
  password: admin
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: practice_app_production
  pool: 5
  username: postgres
  password: admin
  host: localhost
